name: GroupPermission
version: '${project.version}'
main: net.playlegend.grouppermission.GroupPermission
api-version: 1.18
authors: [ pongy20 ]
description: Bewerberplugin für PlayLegend
website: playlegend.net
commands:
  group:
    description: Type /group help to get all detailed information